### ISSUE TITLE
Experiment gets stuck when first goal gives "Aborting" ERROR

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_experiments#1]
I have run the script and things start well (roscore started, rviz, first goal sent, robot starts moving) and an error writing to a file (see #2 )
But then the robot gets stuck almost immediately. After some time it reports aborting current goal and I guess the experiment gets stuck in there. Maybe we need to catch this error to kill the experiment? 

`[ERROR] [1589611402.122171658, 21.329000000]: Aborting because a valid plan could not be found. Even after executing all recovery behaviors`

![rviz_screenshot_2020_05_16-08_57_16](https://user-images.githubusercontent.com/9592617/82113096-8fde1f00-9753-11ea-9851-9c5d96f445d2.png)

**Comment by marioney** [comment]
This was caused by the fake localization, that has wrong initialization parameters.

Should be solved on https://github.com/rosin-project/metacontrol_sim/commit/d320ed15e79ae09b4846b1675c9cf79d2463696c

@chcorbato  Please check it  and close this

**Comment by chcorbato** [comment]
Solved!
