### ISSUE TITLE
Dependencies missing related to navigation packages

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_experiments#14]
I followed the setup instructions.
I have ROS Melodic Desktop installed (NOT full)

When I tried to run the script in [metacontrol_experiments](https://github.com/rosin-project/metacontrol_experiments) 
`./run_single_sim.sh -p 1 -g 2 -n "f1_v1_r1" -o 2 -r "true" -p 1.2`
I got these errors:
```
…                    
ERROR: cannot launch node of type [map_server/map_server]: map_server
…
ERROR: cannot launch node of type [fake_localization/fake_localization]: fake_localization
….
ERROR: cannot launch node of type [laser_filters/scan_to_scan_filter_chain]: laser_filters
```
I installed those packages with `apt` and the errors where solved.

**Comment by marioney** [comment]
OK, I've added those as exec dependencies in https://github.com/rosin-project/metacontrol_experiments/commit/8efa7915415d2c79ce817e6b7d0bfe40fc35ee96

`rosdep` should be able to install them.

**Comment by chcorbato** [comment]
I could not use rosdep before because of the following:
```
rosdep install --from-paths src/ --ignore-src
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
yumi_hw: Cannot locate rosdep definition for [abb_rws_interface]
yumi_cameras: Cannot locate rosdep definition for [abb_rws_interface]
```

**Comment by gavanderhoorn** [comment]
Run `rosdep` with `--skip-keys="abb_rws_interface"`.

**Comment by gavanderhoorn** [comment]
In any case this is not a problem with the navigation packages, so this issue should probably be closed.

**Comment by chcorbato** [comment]
I re-opened it to make sure we have Set up instructions in the README that are as clear and complete as reasonable.

**Comment by gavanderhoorn** [comment]
> I re-opened it to make sure we have Set up instructions in the README that are as clear and complete as reasonable.

The issue title states the dependencies of the navigation packages are incorrect.

Nothing about the readme.

**Comment by marioney** [comment]
Maybe we can move this discussion to https://github.com/rosin-project/metacontrol_sim/issues/44, as they seem to be closely related.

**Comment by chcorbato** [comment]
Good points, moving the discussion to https://github.com/rosin-project/metacontrol_sim/issues/44
