### ISSUE TITLE
experiment scripts fail with new way to load OWL file from absolute path

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_experiments#16]
https://github.com/rosin-project/metacontrol_experiments/blob/6fe326461f5db39d873178a2bb982175e5cdf608/run_reasoner.sh#L154
and
https://github.com/rosin-project/metacontrol_experiments/blob/e4731edfbfd8c216e4cbba485e8aede748d0a828/run_single_sim.sh#L164

See https://github.com/tud-cor/mc_mros_reasoner/issues/80 for details

**Comment by chcorbato** [comment]
@marioney see pull request #17

**Comment by marioney** [comment]
@chcorbato  I think we can close this.  The OWL file should be correctly set in https://github.com/rosin-project/metacontrol_experiments/commit/12b2419c4b54267ab35037ffcc1ffa4f6e02a6c3

**Comment by chcorbato** [comment]
Agreed.
