### ISSUE TITLE
Rosparameters are not read correcly by the mros_reasoner

### ISSUE THREAD

**Issue by JWijkhuizen** [rosin-project/metacontrol_experiments#20]
Mario proposes this:

> actually, to solve this we need to change the launcher on the `run_single.sh` from this `roslaunch mros1_reasoner run.launch onto:=$(rospack find mros1_reasoner)/scripts/kb.owl;` to this: `roslaunch mros1_reasoner run.launch onto:=$(rospack find mros1_reasoner)/scripts/kb.owl desired_configuration:=$nav_profile;`

But this means that the `check_and_read_parameter( )` function in `ros_reasonoer.py` (mros_reasoner repository) is not working and not used at all.

The problem is due to a missing namespace if I understand correctly. In this line for example: self.grounded_configuration = self.check_and_read_parameter('~desired_configuration')

**Comment by marioney** [comment]
> But this means that the `check_and_read_parameter( )` function in `ros_reasonoer.py` (mros_reasoner repository) is not working and not used at all.

It does work, but we're not setting the parameters here in the right way.  I'll change them

**Comment by marioney** [comment]
This should be solved by  https://github.com/rosin-project/metacontrol_experiments/commit/12b2419c4b54267ab35037ffcc1ffa4f6e02a6c3

When I run

`./run_single_sim.sh -i 1 -g 1 -n "f1_v2_r2" -o 2 -r "true" -p 1.7 -c "false" `

I'm getting at least one successful reconfiguration

@JWijkhuizen can you check it and let me know if it works for you.

**Comment by gavanderhoorn** [comment]
Are you not using a fork-branch-PR workflow here?

**Comment by marioney** [comment]
> Are you not using a fork-branch-PR workflow here?

No, in this repo I'm pushing directly into master (I know, I know), but I'm the only one making changes here (for now)

**Comment by JWijkhuizen** [comment]
A missing config.sh file is not the problem in my case. So this will not fix it, right? @marioney 

> This should be solved by [12b2419](https://github.com/rosin-project/metacontrol_experiments/commit/12b2419c4b54267ab35037ffcc1ffa4f6e02a6c3)
> 
> When I run
> 
> `./run_single_sim.sh -i 1 -g 1 -n "f1_v2_r2" -o 2 -r "true" -p 1.7 -c "false" `
> 
> I'm getting at least one successful reconfiguration
> 
> @JWijkhuizen can you check it and let me know if it works for you.

**Comment by marioney** [comment]
> A missing config.sh file is not the problem in my case. So this will not fix it, right? @marioney

Sorry, it was the previous commit, but https://github.com/rosin-project/metacontrol_experiments/commit/12b2419c4b54267ab35037ffcc1ffa4f6e02a6c3 should include the changes to fix the parameters.

**Comment by JWijkhuizen** [comment]
Yes that works for me

**Comment by marioney** [comment]
> Yes that works for me

Great, can you close this then?

**Comment by JWijkhuizen** [comment]
solved by 7a0ecbf01b72d9d4808103fdf634b30f0559484a
