### ISSUE TITLE
diagnostic_status.values[0].key > Index out of Range

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_experiments#24]
when executing:
```
./run_single_sim_desktop.sh
[...]
[ERROR] [1617363701.339231, 0.000000]: bad callback: <bound method RosReasoner.callbackDiagnostics of <mros1_reasoner.ros_reasoner.RosReasoner object at 0x7fa356cde400>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/parallels/models21_ws/src/mros1_reasoner/mros1_reasoner/src/mros1_reasoner/ros_reasoner.py", line 203, in callbackDiagnostics
    rospy.logwarn("Unsupported Message received: %s ", str(diagnostic_status.values[0].key))
IndexError: list index out of range
```
but the experiment seems to continue execution without problems.
Do you also get this error @marioney ?

### Version:
mros1_reasoner:                  https://github.com/tud-cor/mc_mros_reasoner/commit/a84a46aebe9838f3ac04dc9a2a32420df0e90654
metacontrol_experiments:  096d9ed1fc755f43ea6e41901be578b2ec8c327f

**Comment by marioney** [comment]
This was an bug while printing a log message (a copy/paste mistake)

I'm closing this as it should be solved by https://github.com/tud-cor/mc_mros_reasoner/commit/39f7e216c9cc17dea122ca1b3fdbe8a41d248a83
