### ISSUE TITLE
Documentation on how to access the logged experimental data

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_experiments#5]
How/where is the experiments data logged? I could not figure it out. A brief explanation in the README would help.
I just want to check what happened during the experiments.

**Comment by marioney** [comment]
Information about the logs and it's storage location has been added to the Readme in https://github.com/rosin-project/metacontrol_experiments/commit/8b02929d20032250f327fc5f1d1f2a125d171358
