### ISSUE TITLE
add parameter with desired configuration in single_sim.bash

### ISSUE THREAD

**Issue by marioney** [rosin-project/metacontrol_experiments#8]
Single simulation script should set the 

`rosparam set /desired_configuration "f1_v1_r1"`

To the initial configuration launched when the simulation starts

**Comment by marioney** [comment]
The parameter is now set by the run_singe_sim.sh script in https://github.com/rosin-project/metacontrol_experiments/commit/d15d97be8ffdcaca75af39f74f6da3ef6008ac8e

It requires https://github.com/rosin-project/metacontrol_sim/commit/088586bf0ca9852872b5a764e5da3edbb56eca2b and https://github.com/rosin-project/metacontrol_nav/commit/1890fdf83a406d5f8fe86269c039d3a029d9c7ca

@chcorbato can you check it and close this

**Comment by chcorbato** [comment]
Works for me!
